global:
  enabled: true
  name: consul
  datacenter: dc1

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

connectInject:
  default: false
  enabled: true
  namespaceSelector: |
    matchLabels:
      connect-inject: enabled
