image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

persistence:
  enabled: true
  size: "8Gi"
  storageClass: ""

initContainers:
  - name: volume-permissions
    image: busybox:1.35
    command: ["sh", "-c", "chown -R 999:999 /data/db && chmod -R 755 /data/db"]
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: datadir
        mountPath: /data/db

service:
  type: ClusterIP
  port: 27017

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

replicaCount: 1

metrics:
  enabled: false
