apiVersion: v2
name: auth-service
type: application
version: 0.1.0
description: Auth service chart
appVersion: "1.0.0"
dependencies:
  - name: base-service
    version: 0.1.0
    repository: file://../_base-service
